import type {
  AlertItem,
  BrandData,
  DailyProductionPoint,
  DefectRecord,
  ProductionOrder,
  Site,
  Stage,
  StageVolume,
} from './types';

export const STAGES: Stage[] = [
  { id: 'knit', name: 'Tricotage', key: 'knit', icon: '🔄', color: '#3b82f6' },
  { id: 'dye', name: 'Teinture', key: 'dye', icon: '🎨', color: '#8b5cf6' },
  { id: 'wash', name: 'Délavage', key: 'wash', icon: '💧', color: '#06b6d4' },
  { id: 'print', name: 'Sérigraphie', key: 'print', icon: '🖨️', color: '#f59e0b' },
  { id: 'cut', name: 'Coupe', key: 'cut', icon: '✂️', color: '#ef4444' },
  { id: 'sew', name: 'Confection', key: 'sew', icon: '🪡', color: '#10b981' },
  { id: 'finish', name: 'Finissage', key: 'finish', icon: '🏁', color: '#64748b' },
];

export const SITES: Site[] = [
  {
    id: 'mt-main',
    name: 'Menzel Temime — Bonneterie',
    location: 'Menzel Temime, Tunisie',
    focus: ['Tricotage', 'Teinture'],
    employees: 1450,
    machines: 420,
    status: 'optimal',
    utilization: 87,
    defectRate: 1.8,
    onSchedule: true,
  },
  {
    id: 'mt-conf',
    name: 'Menzel Temime — Confection',
    location: 'Menzel Temime, Tunisie',
    focus: ['Coupe', 'Confection'],
    employees: 1650,
    machines: 930,
    status: 'watch',
    utilization: 82,
    defectRate: 2.6,
    onSchedule: true,
  },
  {
    id: 'mb-knit',
    name: 'Menzel Bouzelfa — Tricot',
    location: 'Menzel Bouzelfa, Tunisie',
    focus: ['Tricotage', 'Filature'],
    employees: 420,
    machines: 180,
    status: 'optimal',
    utilization: 91,
    defectRate: 1.2,
    onSchedule: true,
  },
  {
    id: 'mb-fin',
    name: 'Menzel Bouzelfa — Finissage',
    location: 'Menzel Bouzelfa, Tunisie',
    focus: ['Délavage', 'Finissage'],
    employees: 380,
    machines: 95,
    status: 'attention',
    utilization: 74,
    defectRate: 4.1,
    onSchedule: false,
  },
  {
    id: 'mb-print',
    name: 'Menzel Bouzelfa — Sérigraphie',
    location: 'Menzel Bouzelfa, Tunisie',
    focus: ['Sérigraphie'],
    employees: 120,
    machines: 28,
    status: 'watch',
    utilization: 79,
    defectRate: 3.2,
    onSchedule: true,
  },
  {
    id: 'mt-dye',
    name: 'Menzel Temime — Teinturerie',
    location: 'Menzel Temime, Tunisie',
    focus: ['Teinture'],
    employees: 240,
    machines: 54,
    status: 'optimal',
    utilization: 88,
    defectRate: 1.5,
    onSchedule: true,
  },
  {
    id: 'mt-cutt',
    name: 'Menzel Temime — Coupe',
    location: 'Menzel Temime, Tunisie',
    focus: ['Coupe'],
    employees: 180,
    machines: 32,
    status: 'optimal',
    utilization: 85,
    defectRate: 1.4,
    onSchedule: true,
  },
  {
    id: 'mb-simple',
    name: 'Menzel Bouzelfa — Confection 2',
    location: 'Menzel Bouzelfa, Tunisie',
    focus: ['Confection'],
    employees: 820,
    machines: 410,
    status: 'watch',
    utilization: 80,
    defectRate: 2.4,
    onSchedule: true,
  },
];

export const ORDERS: ProductionOrder[] = [
  {
    id: 'ord-001',
    reference: 'PO-LCO-2214',
    brand: 'Lacoste',
    client: 'Lacoste S.A.S.',
    product: 'Polo SS Classic',
    quantity: 85000,
    unit: 'pièces',
    siteId: 'mt-conf',
    stage: 'Confection',
    progressPct: 68,
    dueDate: '2026-10-12',
    startedDate: '2026-08-20',
    status: 'on_track',
    priority: 'high',
    defects: 412,
    colorways: 6,
  },
  {
    id: 'ord-002',
    reference: 'PO-ADS-0887',
    brand: 'Adidas',
    client: 'Adidas AG',
    product: 'Tee Essential 3-Stripes',
    quantity: 120000,
    unit: 'pièces',
    siteId: 'mb-simple',
    stage: 'Confection',
    progressPct: 45,
    dueDate: '2026-10-28',
    startedDate: '2026-09-01',
    status: 'on_track',
    priority: 'critical',
    defects: 890,
    colorways: 9,
  },
  {
    id: 'ord-003',
    reference: 'PO-GST-1342',
    brand: 'G-Star RAW',
    client: 'G-Star International',
    product: 'Denim Jacket 3301',
    quantity: 35000,
    unit: 'pièces',
    siteId: 'mb-fin',
    stage: 'Finissage',
    progressPct: 52,
    dueDate: '2026-10-18',
    startedDate: '2026-08-15',
    status: 'at_risk',
    priority: 'high',
    defects: 1420,
    colorways: 4,
  },
  {
    id: 'ord-004',
    reference: 'PO-PSK-0765',
    brand: 'Paul & Shark',
    client: 'Dama S.p.A.',
    product: 'Windbreaker Tech Shell',
    quantity: 18000,
    unit: 'pièces',
    siteId: 'mt-conf',
    stage: 'Coupe',
    progressPct: 31,
    dueDate: '2026-11-05',
    startedDate: '2026-09-12',
    status: 'on_track',
    priority: 'medium',
    defects: 96,
    colorways: 3,
  },
  {
    id: 'ord-005',
    reference: 'PO-KLF-0512',
    brand: 'Karl Lagerfeld',
    client: 'KARL LAGERFELD SAS',
    product: 'Knitted Blazer K/Odyssey',
    quantity: 12000,
    unit: 'pièces',
    siteId: 'mt-main',
    stage: 'Tricotage',
    progressPct: 88,
    dueDate: '2026-09-30',
    startedDate: '2026-08-05',
    status: 'on_track',
    priority: 'medium',
    defects: 55,
    colorways: 2,
  },
  {
    id: 'ord-006',
    reference: 'PO-LCO-2281',
    brand: 'Lacoste',
    client: 'Lacoste S.A.S.',
    product: 'Long Sleeve Piqué',
    quantity: 62000,
    unit: 'pièces',
    siteId: 'mt-conf',
    stage: 'Teinture',
    progressPct: 74,
    dueDate: '2026-10-15',
    startedDate: '2026-08-25',
    status: 'on_track',
    priority: 'high',
    defects: 310,
    colorways: 5,
  },
  {
    id: 'ord-007',
    reference: 'PO-ADS-0912',
    brand: 'Adidas',
    client: 'Adidas AG',
    product: 'Hoodie Essentials Fleece',
    quantity: 75000,
    unit: 'pièces',
    siteId: 'mb-simple',
    stage: 'Confection',
    progressPct: 15,
    dueDate: '2026-11-20',
    startedDate: '2026-09-15',
    status: 'on_track',
    priority: 'medium',
    defects: 0,
    colorways: 7,
  },
  {
    id: 'ord-008',
    reference: 'PO-GST-1417',
    brand: 'G-Star RAW',
    client: 'G-Star International',
    product: 'Slim Jeans Elwood X25',
    quantity: 58000,
    unit: 'pièces',
    siteId: 'mb-fin',
    stage: 'Délavage',
    progressPct: 39,
    dueDate: '2026-10-30',
    startedDate: '2026-09-08',
    status: 'at_risk',
    priority: 'high',
    defects: 960,
    colorways: 4,
  },
  {
    id: 'ord-009',
    reference: 'PO-PSK-0819',
    brand: 'Paul & Shark',
    client: 'Dama S.p.A.',
    product: 'Polo Pique Raincoat',
    quantity: 9500,
    unit: 'pièces',
    siteId: 'mt-main',
    stage: 'Tricotage',
    progressPct: 61,
    dueDate: '2026-10-20',
    startedDate: '2026-09-02',
    status: 'on_track',
    priority: 'medium',
    defects: 44,
    colorways: 3,
  },
  {
    id: 'ord-010',
    reference: 'PO-KLF-0580',
    brand: 'Karl Lagerfeld',
    client: 'KARL LAGERFELD SAS',
    product: 'Chiffon Blouse K/Icons',
    quantity: 7000,
    unit: 'pièces',
    siteId: 'mb-print',
    stage: 'Sérigraphie',
    progressPct: 47,
    dueDate: '2026-10-25',
    startedDate: '2026-09-10',
    status: 'on_track',
    priority: 'low',
    defects: 88,
    colorways: 2,
  },
  {
    id: 'ord-011',
    reference: 'PO-LCO-2355',
    brand: 'Lacoste',
    client: 'Lacoste S.A.S.',
    product: 'Cardigan Cotton+',
    quantity: 30000,
    unit: 'pièces',
    siteId: 'mt-main',
    stage: 'Teinture',
    progressPct: 12,
    dueDate: '2026-11-28',
    startedDate: '2026-09-18',
    status: 'on_track',
    priority: 'low',
    defects: 0,
    colorways: 6,
  },
  {
    id: 'ord-012',
    reference: 'PO-ADS-0945',
    brand: 'Adidas',
    client: 'Adidas AG',
    product: 'Track Jacket Tiro 24',
    quantity: 68000,
    unit: 'pièces',
    siteId: 'mt-dye',
    stage: 'Teinture',
    progressPct: 28,
    dueDate: '2026-11-15',
    startedDate: '2026-09-16',
    status: 'on_track',
    priority: 'high',
    defects: 0,
    colorways: 5,
  },
];

export const DEFECTS: DefectRecord[] = [
  { id: 'def-01', siteId: 'mb-fin', stage: 'Finissage', date: '2026-09-15', type: 'Coulure teinture', count: 148, severity: 'major' },
  { id: 'def-02', siteId: 'mb-fin', stage: 'Délavage', date: '2026-09-15', type: 'Défaut de lavage', count: 96, severity: 'minor' },
  { id: 'def-03', siteId: 'mt-conf', stage: 'Confection', date: '2026-09-15', type: 'Piquage décalé', count: 74, severity: 'minor' },
  { id: 'def-04', siteId: 'mb-print', stage: 'Sérigraphie', date: '2026-09-15', type: 'Écrantage flou', count: 42, severity: 'major' },
  { id: 'def-05', siteId: 'mt-conf', stage: 'Confection', date: '2026-09-14', type: 'Casier cassé', count: 38, severity: 'minor' },
  { id: 'def-06', siteId: 'mb-simple', stage: 'Confection', date: '2026-09-14', type: 'Bordure roulée', count: 85, severity: 'minor' },
  { id: 'def-07', siteId: 'mt-dye', stage: 'Teinture', date: '2026-09-14', type: 'Différence de nuance', count: 22, severity: 'critical' },
  { id: 'def-08', siteId: 'mb-fin', stage: 'Délavage', date: '2026-09-14', type: 'Trous', count: 51, severity: 'major' },
  { id: 'def-09', siteId: 'mt-main', stage: 'Tricotage', date: '2026-09-13', type: 'Trame lâche', count: 18, severity: 'minor' },
  { id: 'def-10', siteId: 'mb-simple', stage: 'Confection', date: '2026-09-13', type: 'Fil tiré', count: 63, severity: 'minor' },
  { id: 'def-11', siteId: 'mb-fin', stage: 'Finissage', date: '2026-09-13', type: 'Vapeur — pliure', count: 77, severity: 'minor' },
  { id: 'def-12', siteId: 'mt-cutt', stage: 'Coupe', date: '2026-09-12', type: 'Coupe déviée', count: 12, severity: 'critical' },
  { id: 'def-13', siteId: 'mb-print', stage: 'Sérigraphie', date: '2026-09-12', type: 'Manque de pigment', count: 29, severity: 'major' },
  { id: 'def-14', siteId: 'mt-conf', stage: 'Confection', date: '2026-09-11', type: 'Piquage décalé', count: 91, severity: 'minor' },
  { id: 'def-15', siteId: 'mb-fin', stage: 'Délavage', date: '2026-09-11', type: 'Eau stagnante', count: 33, severity: 'major' },
];

export const DAILY_PRODUCTION: DailyProductionPoint[] = [
  { date: 'Sep 1', planned: 42000, actual: 43300 },
  { date: 'Sep 2', planned: 42000, actual: 40600 },
  { date: 'Sep 3', planned: 42000, actual: 44100 },
  { date: 'Sep 4', planned: 44000, actual: 45200 },
  { date: 'Sep 5', planned: 44000, actual: 42800 },
  { date: 'Sep 6', planned: 30000, actual: 31200 },
  { date: 'Sep 7', planned: 44000, actual: 46800 },
  { date: 'Sep 8', planned: 46000, actual: 44100 },
  { date: 'Sep 9', planned: 46000, actual: 47700 },
  { date: 'Sep 10', planned: 46000, actual: 45200 },
  { date: 'Sep 11', planned: 48000, actual: 49800 },
  { date: 'Sep 12', planned: 48000, actual: 46300 },
  { date: 'Sep 13', planned: 36000, actual: 37100 },
  { date: 'Sep 14', planned: 48000, actual: 50200 },
  { date: 'Sep 15', planned: 48000, actual: 47400 },
  { date: 'Sep 16', planned: 48000, actual: 50900 },
  { date: 'Sep 17', planned: 50000, actual: 48300 },
  { date: 'Sep 18', planned: 50000, actual: 0 },
];

export const STAGE_VOLUMES: StageVolume[] = [
  { stage: 'Tricotage', units: 248000, color: '#3b82f6' },
  { stage: 'Teinture', units: 216000, color: '#8b5cf6' },
  { stage: 'Délavage', units: 132000, color: '#06b6d4' },
  { stage: 'Sérigraphie', units: 61000, color: '#f59e0b' },
  { stage: 'Coupe', units: 198000, color: '#ef4444' },
  { stage: 'Confection', units: 293000, color: '#10b981' },
  { stage: 'Finissage', units: 172000, color: '#64748b' },
];

export const BRANDS: BrandData[] = [
  { brand: 'Lacoste', orders: 3, units: 177000, onTime: 94, color: '#22c55e' },
  { brand: 'Adidas', orders: 3, units: 263000, onTime: 88, color: '#3b82f6' },
  { brand: 'G-Star RAW', orders: 2, units: 93000, onTime: 72, color: '#f59e0b' },
  { brand: 'Paul & Shark', orders: 2, units: 27500, onTime: 91, color: '#8b5cf6' },
  { brand: 'Karl Lagerfeld', orders: 2, units: 19000, onTime: 96, color: '#06b6d4' },
];

export const ALERTS: AlertItem[] = [
  {
    id: 'alt-01',
    title: 'Risque de retard — G-Star (PO-GST-1342)',
    description: 'Le Finissage est en retard de 3 jours. Taux de défauts de 4,1% sur Menzel Bouzelfa — Finissage.',
    severity: 'critical',
    time: 'il y a 25 min',
    siteId: 'mb-fin',
    stage: 'Finissage',
    type: 'delay',
  },
  {
    id: 'alt-02',
    title: 'Écart de production — Confection 2',
    description: 'Adidas PO-ADS-0887 à 45% vs 52% planifié. Capacité machine insuffisante sur l’atelier 4.',
    severity: 'warning',
    time: 'il y a 1 h',
    siteId: 'mb-simple',
    stage: 'Confection',
    type: 'capacity',
  },
  {
    id: 'alt-03',
    title: 'Taux de rebut élevé — Sérigraphie',
    description: 'Écrantage flou sur 42 pièces aujourd’hui. Maintenance préventive du poste 7 recommandée.',
    severity: 'warning',
    time: 'il y a 2 h',
    siteId: 'mb-print',
    stage: 'Sérigraphie',
    type: 'quality',
  },
  {
    id: 'alt-04',
    title: 'Différence de nuance — Teinture',
    description: '22 pièces classées critiques (PO-LCO-2281). Contrast controle requis sur le bain 12.',
    severity: 'critical',
    time: 'il y a 3 h',
    siteId: 'mt-dye',
    stage: 'Teinture',
    type: 'quality',
  },
  {
    id: 'alt-05',
    title: 'Machine 214 — maintenance prévue',
    description: 'Ricam 25T (Confection) : remplacement aiguille plateau dans 48h pour éviter les arrêts.',
    severity: 'info',
    time: 'il y a 5 h',
    siteId: 'mt-conf',
    stage: 'Confection',
    type: 'maintenance',
  },
];

export const formatNumber = (n: number): string => {
  return new Intl.NumberFormat('en-US').format(n);
};

export const getSiteById = (id: string): Site | undefined =>
  SITES.find(s => s.id === id);

export const getStageById = (id: string): Stage | undefined =>
  STAGES.find(s => s.id === id);

export const getBrandColor = (brand: string): string => {
  const b = BRANDS.find(x => x.brand === brand);
  return b?.color ?? '#64748b';
};

export const totalUnits = ORDERS.reduce((acc, o) => acc + o.quantity, 0);
export const totalOrders = ORDERS.length;
export const activeOrders = ORDERS.filter(o => o.status !== 'delayed').length;
export const atRiskOrders = ORDERS.filter(o => o.status === 'at_risk').length;
export const avgOnTimeRate =
  BRANDS.reduce((acc, b) => acc + b.onTime, 0) / BRANDS.length;

export const todayDefects = DEFECTS.filter(d => d.date === '2026-09-15')
  .reduce((acc, d) => acc + d.count, 0);
export const todayProduction = DAILY_PRODUCTION[16].actual; // Sep 17